[versions]
agp = "9.0.1"
snakeyaml = "2.6"
kotlinpoet = "2.2.0"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
